project_id = "pzjleqrayhfpqlzwqdqm"

[functions.create-client-account]
verify_jwt = true

[functions.delete-client-account]
verify_jwt = true

[functions.manage-utenza-account]
verify_jwt = true

[functions.utenza-login]
verify_jwt = false

[functions.ai-refine]
verify_jwt = true

[functions.create-test-ncc-accounts]
verify_jwt = false

[functions.create-autista-account]
verify_jwt = true

[functions.analyze-scontrino]
verify_jwt = true

